version: '2.2'
services:
  wallet-mongo:
    container_name: wallet-mongo
    image: mongo
    restart: always
    volumes:
      - wallet-mongodb-vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier

  wallet-node:
    container_name: wallet-node
    restart: always
    depends_on:
      - wallet-mongo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
    env_file:
      - .env
    cpus: 2
    mem_limit: 1024m


volumes:
  wallet-mongodb-vol:

networks:
  services-tier: